#include <GarrysMod/Lua/Interface.h>
#include <curl/curl.h>
#include <string>

using namespace GarrysMod;

#define ADD_NUM(key, val)     \
    {                         \
        LUA->PushString(key); \
        LUA->PushNumber(val); \
        LUA->SetTable(-3);    \
    }
#define ADD_FUN(key, val)        \
    {                            \
        LUA->PushString(key);    \
        LUA->PushCFunction(val); \
        LUA->SetTable(-3);       \
    }

static int typeid_curl;

void log(Lua::ILuaBase* LUA, std::string message)
{
    LUA->PushSpecial(Lua::SPECIAL_GLOB);
    LUA->GetField(-1, "print");
    LUA->PushString(("[curl] " + message).c_str());
    LUA->Call(1, 0);
    LUA->Pop();
}

LUA_FUNCTION(lua_curl_easy_init)
{
    CURL* curl = curl_easy_init();

    LUA->PushUserType(curl, typeid_curl);
    return 1;
}

LUA_FUNCTION(lua_curl_easy_cleanup)
{
    CURL* curl = LUA->GetUserType<CURL>(1, typeid_curl);

    if (curl == NULL)
        LUA->ArgError(1, "Not a curl object (or object was NULL).");

    curl_easy_cleanup(curl);
    return 0;
}

LUA_FUNCTION(lua_curl_easy_perform)
{
    CURL* curl = LUA->GetUserType<CURL>(1, typeid_curl);

    if (curl == NULL)
        LUA->ArgError(1, "Not a curl object (or object was NULL).");

    CURLcode res = curl_easy_perform(curl);

    LUA->PushNumber(res);
    return 1;
}

LUA_FUNCTION(lua_curl_easy_setopt)
{
    CURL* curl = LUA->GetUserType<CURL>(1, typeid_curl);

    if (curl == NULL)
        LUA->ArgError(1, "Not a curl object (or object was NULL).");

    CURLoption option = (CURLoption)LUA->CheckNumber(2);

    CURLcode res;
    if (LUA->IsType(3, Lua::Type::String))
        res = curl_easy_setopt(curl, option, LUA->GetString(3));
    else if (LUA->IsType(3, Lua::Type::Number))
        res = curl_easy_setopt(curl, option, LUA->GetNumber(3));
    else if (LUA->IsType(3, Lua::Type::Bool))
        res = curl_easy_setopt(curl, option, LUA->GetBool(3));
    else
        LUA->ArgError(3, "Value is not one of the supported types.");

    LUA->PushNumber(res);
    return 1;
}

LUA_FUNCTION(lua_curl_easy_strerror)
{
    CURLcode res = (CURLcode)LUA->CheckNumber(1);

    char const* error = curl_easy_strerror(res);

    LUA->PushString(error);
    return 1;
}

GMOD_MODULE_OPEN()
{
    curl_global_init(CURL_GLOBAL_ALL);

    // Initialize custom userdata types
    typeid_curl = LUA->CreateMetaTable("CURL");
    LUA->Pop();

    // We are working on the global table today
    LUA->PushSpecial(Lua::SPECIAL_GLOB);

    ADD_NUM("CURLOPT_WRITEDATA", CURLOPT_WRITEDATA);
    ADD_NUM("CURLOPT_URL", CURLOPT_URL);
    ADD_NUM("CURLOPT_PORT", CURLOPT_PORT);
    ADD_NUM("CURLOPT_PROXY", CURLOPT_PROXY);
    ADD_NUM("CURLOPT_USERPWD", CURLOPT_USERPWD);
    ADD_NUM("CURLOPT_PROXYUSERPWD", CURLOPT_PROXYUSERPWD);
    ADD_NUM("CURLOPT_RANGE", CURLOPT_RANGE);
    ADD_NUM("CURLOPT_READDATA", CURLOPT_READDATA);
    ADD_NUM("CURLOPT_ERRORBUFFER", CURLOPT_ERRORBUFFER);
    ADD_NUM("CURLOPT_WRITEFUNCTION", CURLOPT_WRITEFUNCTION);
    ADD_NUM("CURLOPT_READFUNCTION", CURLOPT_READFUNCTION);
    ADD_NUM("CURLOPT_TIMEOUT", CURLOPT_TIMEOUT);
    ADD_NUM("CURLOPT_INFILESIZE", CURLOPT_INFILESIZE);
    ADD_NUM("CURLOPT_POSTFIELDS", CURLOPT_POSTFIELDS);
    ADD_NUM("CURLOPT_REFERER", CURLOPT_REFERER);
    ADD_NUM("CURLOPT_FTPPORT", CURLOPT_FTPPORT);
    ADD_NUM("CURLOPT_USERAGENT", CURLOPT_USERAGENT);
    ADD_NUM("CURLOPT_LOW_SPEED_LIMIT", CURLOPT_LOW_SPEED_LIMIT);
    ADD_NUM("CURLOPT_LOW_SPEED_TIME", CURLOPT_LOW_SPEED_TIME);
    ADD_NUM("CURLOPT_RESUME_FROM", CURLOPT_RESUME_FROM);
    ADD_NUM("CURLOPT_COOKIE", CURLOPT_COOKIE);
    ADD_NUM("CURLOPT_HTTPHEADER", CURLOPT_HTTPHEADER);
    ADD_NUM("CURLOPT_HTTPPOST", CURLOPT_HTTPPOST);
    ADD_NUM("CURLOPT_SSLCERT", CURLOPT_SSLCERT);
    ADD_NUM("CURLOPT_KEYPASSWD", CURLOPT_KEYPASSWD);
    ADD_NUM("CURLOPT_CRLF", CURLOPT_CRLF);
    ADD_NUM("CURLOPT_QUOTE", CURLOPT_QUOTE);
    ADD_NUM("CURLOPT_HEADERDATA", CURLOPT_HEADERDATA);
    ADD_NUM("CURLOPT_COOKIEFILE", CURLOPT_COOKIEFILE);
    ADD_NUM("CURLOPT_SSLVERSION", CURLOPT_SSLVERSION);
    ADD_NUM("CURLOPT_TIMECONDITION", CURLOPT_TIMECONDITION);
    ADD_NUM("CURLOPT_TIMEVALUE", CURLOPT_TIMEVALUE);
    ADD_NUM("CURLOPT_CUSTOMREQUEST", CURLOPT_CUSTOMREQUEST);
    ADD_NUM("CURLOPT_STDERR", CURLOPT_STDERR);
    ADD_NUM("CURLOPT_POSTQUOTE", CURLOPT_POSTQUOTE);
    ADD_NUM("CURLOPT_OBSOLETE40", CURLOPT_OBSOLETE40);
    ADD_NUM("CURLOPT_VERBOSE", CURLOPT_VERBOSE);
    ADD_NUM("CURLOPT_HEADER", CURLOPT_HEADER);
    ADD_NUM("CURLOPT_NOPROGRESS", CURLOPT_NOPROGRESS);
    ADD_NUM("CURLOPT_NOBODY", CURLOPT_NOBODY);
    ADD_NUM("CURLOPT_FAILONERROR", CURLOPT_FAILONERROR);
    ADD_NUM("CURLOPT_UPLOAD", CURLOPT_UPLOAD);
    ADD_NUM("CURLOPT_POST", CURLOPT_POST);
    ADD_NUM("CURLOPT_DIRLISTONLY", CURLOPT_DIRLISTONLY);
    ADD_NUM("CURLOPT_APPEND", CURLOPT_APPEND);
    ADD_NUM("CURLOPT_NETRC", CURLOPT_NETRC);
    ADD_NUM("CURLOPT_FOLLOWLOCATION", CURLOPT_FOLLOWLOCATION);
    ADD_NUM("CURLOPT_TRANSFERTEXT", CURLOPT_TRANSFERTEXT);
    ADD_NUM("CURLOPT_PUT", CURLOPT_PUT);
    ADD_NUM("CURLOPT_PROGRESSFUNCTION", CURLOPT_PROGRESSFUNCTION);
    ADD_NUM("CURLOPT_XFERINFODATA", CURLOPT_XFERINFODATA);
    ADD_NUM("CURLOPT_AUTOREFERER", CURLOPT_AUTOREFERER);
    ADD_NUM("CURLOPT_PROXYPORT", CURLOPT_PROXYPORT);
    ADD_NUM("CURLOPT_POSTFIELDSIZE", CURLOPT_POSTFIELDSIZE);
    ADD_NUM("CURLOPT_HTTPPROXYTUNNEL", CURLOPT_HTTPPROXYTUNNEL);
    ADD_NUM("CURLOPT_INTERFACE", CURLOPT_INTERFACE);
    ADD_NUM("CURLOPT_KRBLEVEL", CURLOPT_KRBLEVEL);
    ADD_NUM("CURLOPT_SSL_VERIFYPEER", CURLOPT_SSL_VERIFYPEER);
    ADD_NUM("CURLOPT_CAINFO", CURLOPT_CAINFO);
    ADD_NUM("CURLOPT_MAXREDIRS", CURLOPT_MAXREDIRS);
    ADD_NUM("CURLOPT_FILETIME", CURLOPT_FILETIME);
    ADD_NUM("CURLOPT_TELNETOPTIONS", CURLOPT_TELNETOPTIONS);
    ADD_NUM("CURLOPT_MAXCONNECTS", CURLOPT_MAXCONNECTS);
    ADD_NUM("CURLOPT_OBSOLETE72", CURLOPT_OBSOLETE72);
    ADD_NUM("CURLOPT_FRESH_CONNECT", CURLOPT_FRESH_CONNECT);
    ADD_NUM("CURLOPT_FORBID_REUSE", CURLOPT_FORBID_REUSE);
    ADD_NUM("CURLOPT_RANDOM_FILE", CURLOPT_RANDOM_FILE);
    ADD_NUM("CURLOPT_EGDSOCKET", CURLOPT_EGDSOCKET);
    ADD_NUM("CURLOPT_CONNECTTIMEOUT", CURLOPT_CONNECTTIMEOUT);
    ADD_NUM("CURLOPT_HEADERFUNCTION", CURLOPT_HEADERFUNCTION);
    ADD_NUM("CURLOPT_HTTPGET", CURLOPT_HTTPGET);
    ADD_NUM("CURLOPT_SSL_VERIFYHOST", CURLOPT_SSL_VERIFYHOST);
    ADD_NUM("CURLOPT_COOKIEJAR", CURLOPT_COOKIEJAR);
    ADD_NUM("CURLOPT_SSL_CIPHER_LIST", CURLOPT_SSL_CIPHER_LIST);
    ADD_NUM("CURLOPT_HTTP_VERSION", CURLOPT_HTTP_VERSION);
    ADD_NUM("CURLOPT_FTP_USE_EPSV", CURLOPT_FTP_USE_EPSV);
    ADD_NUM("CURLOPT_SSLCERTTYPE", CURLOPT_SSLCERTTYPE);
    ADD_NUM("CURLOPT_SSLKEY", CURLOPT_SSLKEY);
    ADD_NUM("CURLOPT_SSLKEYTYPE", CURLOPT_SSLKEYTYPE);
    ADD_NUM("CURLOPT_SSLENGINE", CURLOPT_SSLENGINE);
    ADD_NUM("CURLOPT_SSLENGINE_DEFAULT", CURLOPT_SSLENGINE_DEFAULT);
    ADD_NUM("CURLOPT_DNS_USE_GLOBAL_CACHE", CURLOPT_DNS_USE_GLOBAL_CACHE);
    ADD_NUM("CURLOPT_DNS_CACHE_TIMEOUT", CURLOPT_DNS_CACHE_TIMEOUT);
    ADD_NUM("CURLOPT_PREQUOTE", CURLOPT_PREQUOTE);
    ADD_NUM("CURLOPT_DEBUGFUNCTION", CURLOPT_DEBUGFUNCTION);
    ADD_NUM("CURLOPT_DEBUGDATA", CURLOPT_DEBUGDATA);
    ADD_NUM("CURLOPT_COOKIESESSION", CURLOPT_COOKIESESSION);
    ADD_NUM("CURLOPT_CAPATH", CURLOPT_CAPATH);
    ADD_NUM("CURLOPT_BUFFERSIZE", CURLOPT_BUFFERSIZE);
    ADD_NUM("CURLOPT_NOSIGNAL", CURLOPT_NOSIGNAL);
    ADD_NUM("CURLOPT_SHARE", CURLOPT_SHARE);
    ADD_NUM("CURLOPT_PROXYTYPE", CURLOPT_PROXYTYPE);
    ADD_NUM("CURLOPT_ACCEPT_ENCODING", CURLOPT_ACCEPT_ENCODING);
    ADD_NUM("CURLOPT_PRIVATE", CURLOPT_PRIVATE);
    ADD_NUM("CURLOPT_HTTP200ALIASES", CURLOPT_HTTP200ALIASES);
    ADD_NUM("CURLOPT_UNRESTRICTED_AUTH", CURLOPT_UNRESTRICTED_AUTH);
    ADD_NUM("CURLOPT_FTP_USE_EPRT", CURLOPT_FTP_USE_EPRT);
    ADD_NUM("CURLOPT_HTTPAUTH", CURLOPT_HTTPAUTH);
    ADD_NUM("CURLOPT_SSL_CTX_FUNCTION", CURLOPT_SSL_CTX_FUNCTION);
    ADD_NUM("CURLOPT_SSL_CTX_DATA", CURLOPT_SSL_CTX_DATA);
    ADD_NUM("CURLOPT_FTP_CREATE_MISSING_DIRS", CURLOPT_FTP_CREATE_MISSING_DIRS);
    ADD_NUM("CURLOPT_PROXYAUTH", CURLOPT_PROXYAUTH);
    ADD_NUM("CURLOPT_SERVER_RESPONSE_TIMEOUT", CURLOPT_SERVER_RESPONSE_TIMEOUT);
    ADD_NUM("CURLOPT_IPRESOLVE", CURLOPT_IPRESOLVE);
    ADD_NUM("CURLOPT_MAXFILESIZE", CURLOPT_MAXFILESIZE);
    ADD_NUM("CURLOPT_INFILESIZE_LARGE", CURLOPT_INFILESIZE_LARGE);
    ADD_NUM("CURLOPT_RESUME_FROM_LARGE", CURLOPT_RESUME_FROM_LARGE);
    ADD_NUM("CURLOPT_MAXFILESIZE_LARGE", CURLOPT_MAXFILESIZE_LARGE);
    ADD_NUM("CURLOPT_NETRC_FILE", CURLOPT_NETRC_FILE);
    ADD_NUM("CURLOPT_USE_SSL", CURLOPT_USE_SSL);
    ADD_NUM("CURLOPT_POSTFIELDSIZE_LARGE", CURLOPT_POSTFIELDSIZE_LARGE);
    ADD_NUM("CURLOPT_TCP_NODELAY", CURLOPT_TCP_NODELAY);
    ADD_NUM("CURLOPT_FTPSSLAUTH", CURLOPT_FTPSSLAUTH);
    ADD_NUM("CURLOPT_IOCTLFUNCTION", CURLOPT_IOCTLFUNCTION);
    ADD_NUM("CURLOPT_IOCTLDATA", CURLOPT_IOCTLDATA);
    ADD_NUM("CURLOPT_FTP_ACCOUNT", CURLOPT_FTP_ACCOUNT);
    ADD_NUM("CURLOPT_COOKIELIST", CURLOPT_COOKIELIST);
    ADD_NUM("CURLOPT_IGNORE_CONTENT_LENGTH", CURLOPT_IGNORE_CONTENT_LENGTH);
    ADD_NUM("CURLOPT_FTP_SKIP_PASV_IP", CURLOPT_FTP_SKIP_PASV_IP);
    ADD_NUM("CURLOPT_FTP_FILEMETHOD", CURLOPT_FTP_FILEMETHOD);
    ADD_NUM("CURLOPT_LOCALPORT", CURLOPT_LOCALPORT);
    ADD_NUM("CURLOPT_LOCALPORTRANGE", CURLOPT_LOCALPORTRANGE);
    ADD_NUM("CURLOPT_CONNECT_ONLY", CURLOPT_CONNECT_ONLY);
    ADD_NUM("CURLOPT_CONV_FROM_NETWORK_FUNCTION", CURLOPT_CONV_FROM_NETWORK_FUNCTION);
    ADD_NUM("CURLOPT_CONV_TO_NETWORK_FUNCTION", CURLOPT_CONV_TO_NETWORK_FUNCTION);
    ADD_NUM("CURLOPT_CONV_FROM_UTF8_FUNCTION", CURLOPT_CONV_FROM_UTF8_FUNCTION);
    ADD_NUM("CURLOPT_MAX_SEND_SPEED_LARGE", CURLOPT_MAX_SEND_SPEED_LARGE);
    ADD_NUM("CURLOPT_MAX_RECV_SPEED_LARGE", CURLOPT_MAX_RECV_SPEED_LARGE);
    ADD_NUM("CURLOPT_FTP_ALTERNATIVE_TO_USER", CURLOPT_FTP_ALTERNATIVE_TO_USER);
    ADD_NUM("CURLOPT_SOCKOPTFUNCTION", CURLOPT_SOCKOPTFUNCTION);
    ADD_NUM("CURLOPT_SOCKOPTDATA", CURLOPT_SOCKOPTDATA);
    ADD_NUM("CURLOPT_SSL_SESSIONID_CACHE", CURLOPT_SSL_SESSIONID_CACHE);
    ADD_NUM("CURLOPT_SSH_AUTH_TYPES", CURLOPT_SSH_AUTH_TYPES);
    ADD_NUM("CURLOPT_SSH_PUBLIC_KEYFILE", CURLOPT_SSH_PUBLIC_KEYFILE);
    ADD_NUM("CURLOPT_SSH_PRIVATE_KEYFILE", CURLOPT_SSH_PRIVATE_KEYFILE);
    ADD_NUM("CURLOPT_FTP_SSL_CCC", CURLOPT_FTP_SSL_CCC);
    ADD_NUM("CURLOPT_TIMEOUT_MS", CURLOPT_TIMEOUT_MS);
    ADD_NUM("CURLOPT_CONNECTTIMEOUT_MS", CURLOPT_CONNECTTIMEOUT_MS);
    ADD_NUM("CURLOPT_HTTP_TRANSFER_DECODING", CURLOPT_HTTP_TRANSFER_DECODING);
    ADD_NUM("CURLOPT_HTTP_CONTENT_DECODING", CURLOPT_HTTP_CONTENT_DECODING);
    ADD_NUM("CURLOPT_NEW_FILE_PERMS", CURLOPT_NEW_FILE_PERMS);
    ADD_NUM("CURLOPT_NEW_DIRECTORY_PERMS", CURLOPT_NEW_DIRECTORY_PERMS);
    ADD_NUM("CURLOPT_POSTREDIR", CURLOPT_POSTREDIR);
    ADD_NUM("CURLOPT_SSH_HOST_PUBLIC_KEY_MD5", CURLOPT_SSH_HOST_PUBLIC_KEY_MD5);
    ADD_NUM("CURLOPT_OPENSOCKETFUNCTION", CURLOPT_OPENSOCKETFUNCTION);
    ADD_NUM("CURLOPT_OPENSOCKETDATA", CURLOPT_OPENSOCKETDATA);
    ADD_NUM("CURLOPT_COPYPOSTFIELDS", CURLOPT_COPYPOSTFIELDS);
    ADD_NUM("CURLOPT_PROXY_TRANSFER_MODE", CURLOPT_PROXY_TRANSFER_MODE);
    ADD_NUM("CURLOPT_SEEKFUNCTION", CURLOPT_SEEKFUNCTION);
    ADD_NUM("CURLOPT_SEEKDATA", CURLOPT_SEEKDATA);
    ADD_NUM("CURLOPT_CRLFILE", CURLOPT_CRLFILE);
    ADD_NUM("CURLOPT_ISSUERCERT", CURLOPT_ISSUERCERT);
    ADD_NUM("CURLOPT_ADDRESS_SCOPE", CURLOPT_ADDRESS_SCOPE);
    ADD_NUM("CURLOPT_CERTINFO", CURLOPT_CERTINFO);
    ADD_NUM("CURLOPT_USERNAME", CURLOPT_USERNAME);
    ADD_NUM("CURLOPT_PASSWORD", CURLOPT_PASSWORD);
    ADD_NUM("CURLOPT_PROXYUSERNAME", CURLOPT_PROXYUSERNAME);
    ADD_NUM("CURLOPT_PROXYPASSWORD", CURLOPT_PROXYPASSWORD);
    ADD_NUM("CURLOPT_NOPROXY", CURLOPT_NOPROXY);
    ADD_NUM("CURLOPT_TFTP_BLKSIZE", CURLOPT_TFTP_BLKSIZE);
    ADD_NUM("CURLOPT_SOCKS5_GSSAPI_SERVICE", CURLOPT_SOCKS5_GSSAPI_SERVICE);
    ADD_NUM("CURLOPT_SOCKS5_GSSAPI_NEC", CURLOPT_SOCKS5_GSSAPI_NEC);
    ADD_NUM("CURLOPT_PROTOCOLS", CURLOPT_PROTOCOLS);
    ADD_NUM("CURLOPT_REDIR_PROTOCOLS", CURLOPT_REDIR_PROTOCOLS);
    ADD_NUM("CURLOPT_SSH_KNOWNHOSTS", CURLOPT_SSH_KNOWNHOSTS);
    ADD_NUM("CURLOPT_SSH_KEYFUNCTION", CURLOPT_SSH_KEYFUNCTION);
    ADD_NUM("CURLOPT_SSH_KEYDATA", CURLOPT_SSH_KEYDATA);
    ADD_NUM("CURLOPT_MAIL_FROM", CURLOPT_MAIL_FROM);
    ADD_NUM("CURLOPT_MAIL_RCPT", CURLOPT_MAIL_RCPT);
    ADD_NUM("CURLOPT_FTP_USE_PRET", CURLOPT_FTP_USE_PRET);
    ADD_NUM("CURLOPT_RTSP_REQUEST", CURLOPT_RTSP_REQUEST);
    ADD_NUM("CURLOPT_RTSP_SESSION_ID", CURLOPT_RTSP_SESSION_ID);
    ADD_NUM("CURLOPT_RTSP_STREAM_URI", CURLOPT_RTSP_STREAM_URI);
    ADD_NUM("CURLOPT_RTSP_TRANSPORT", CURLOPT_RTSP_TRANSPORT);
    ADD_NUM("CURLOPT_RTSP_CLIENT_CSEQ", CURLOPT_RTSP_CLIENT_CSEQ);
    ADD_NUM("CURLOPT_RTSP_SERVER_CSEQ", CURLOPT_RTSP_SERVER_CSEQ);
    ADD_NUM("CURLOPT_INTERLEAVEDATA", CURLOPT_INTERLEAVEDATA);
    ADD_NUM("CURLOPT_INTERLEAVEFUNCTION", CURLOPT_INTERLEAVEFUNCTION);
    ADD_NUM("CURLOPT_WILDCARDMATCH", CURLOPT_WILDCARDMATCH);
    ADD_NUM("CURLOPT_CHUNK_BGN_FUNCTION", CURLOPT_CHUNK_BGN_FUNCTION);
    ADD_NUM("CURLOPT_CHUNK_END_FUNCTION", CURLOPT_CHUNK_END_FUNCTION);
    ADD_NUM("CURLOPT_FNMATCH_FUNCTION", CURLOPT_FNMATCH_FUNCTION);
    ADD_NUM("CURLOPT_CHUNK_DATA", CURLOPT_CHUNK_DATA);
    ADD_NUM("CURLOPT_FNMATCH_DATA", CURLOPT_FNMATCH_DATA);
    ADD_NUM("CURLOPT_RESOLVE", CURLOPT_RESOLVE);
    ADD_NUM("CURLOPT_TLSAUTH_USERNAME", CURLOPT_TLSAUTH_USERNAME);
    ADD_NUM("CURLOPT_TLSAUTH_PASSWORD", CURLOPT_TLSAUTH_PASSWORD);
    ADD_NUM("CURLOPT_TLSAUTH_TYPE", CURLOPT_TLSAUTH_TYPE);
    ADD_NUM("CURLOPT_TRANSFER_ENCODING", CURLOPT_TRANSFER_ENCODING);
    ADD_NUM("CURLOPT_CLOSESOCKETFUNCTION", CURLOPT_CLOSESOCKETFUNCTION);
    ADD_NUM("CURLOPT_CLOSESOCKETDATA", CURLOPT_CLOSESOCKETDATA);
    ADD_NUM("CURLOPT_GSSAPI_DELEGATION", CURLOPT_GSSAPI_DELEGATION);
    ADD_NUM("CURLOPT_DNS_SERVERS", CURLOPT_DNS_SERVERS);
    ADD_NUM("CURLOPT_ACCEPTTIMEOUT_MS", CURLOPT_ACCEPTTIMEOUT_MS);
    ADD_NUM("CURLOPT_TCP_KEEPALIVE", CURLOPT_TCP_KEEPALIVE);
    ADD_NUM("CURLOPT_TCP_KEEPIDLE", CURLOPT_TCP_KEEPIDLE);
    ADD_NUM("CURLOPT_TCP_KEEPINTVL", CURLOPT_TCP_KEEPINTVL);
    ADD_NUM("CURLOPT_SSL_OPTIONS", CURLOPT_SSL_OPTIONS);
    ADD_NUM("CURLOPT_MAIL_AUTH", CURLOPT_MAIL_AUTH);
    ADD_NUM("CURLOPT_SASL_IR", CURLOPT_SASL_IR);
    ADD_NUM("CURLOPT_XFERINFOFUNCTION", CURLOPT_XFERINFOFUNCTION);
    ADD_NUM("CURLOPT_XOAUTH2_BEARER", CURLOPT_XOAUTH2_BEARER);
    ADD_NUM("CURLOPT_DNS_INTERFACE", CURLOPT_DNS_INTERFACE);
    ADD_NUM("CURLOPT_DNS_LOCAL_IP4", CURLOPT_DNS_LOCAL_IP4);
    ADD_NUM("CURLOPT_DNS_LOCAL_IP6", CURLOPT_DNS_LOCAL_IP6);
    ADD_NUM("CURLOPT_LOGIN_OPTIONS", CURLOPT_LOGIN_OPTIONS);
    ADD_NUM("CURLOPT_SSL_ENABLE_NPN", CURLOPT_SSL_ENABLE_NPN);
    ADD_NUM("CURLOPT_SSL_ENABLE_ALPN", CURLOPT_SSL_ENABLE_ALPN);
    ADD_NUM("CURLOPT_EXPECT_100_TIMEOUT_MS", CURLOPT_EXPECT_100_TIMEOUT_MS);
    ADD_NUM("CURLOPT_PROXYHEADER", CURLOPT_PROXYHEADER);
    ADD_NUM("CURLOPT_HEADEROPT", CURLOPT_HEADEROPT);
    ADD_NUM("CURLOPT_PINNEDPUBLICKEY", CURLOPT_PINNEDPUBLICKEY);
    ADD_NUM("CURLOPT_UNIX_SOCKET_PATH", CURLOPT_UNIX_SOCKET_PATH);
    ADD_NUM("CURLOPT_SSL_VERIFYSTATUS", CURLOPT_SSL_VERIFYSTATUS);
    ADD_NUM("CURLOPT_SSL_FALSESTART", CURLOPT_SSL_FALSESTART);
    ADD_NUM("CURLOPT_PATH_AS_IS", CURLOPT_PATH_AS_IS);
    ADD_NUM("CURLOPT_PROXY_SERVICE_NAME", CURLOPT_PROXY_SERVICE_NAME);
    ADD_NUM("CURLOPT_SERVICE_NAME", CURLOPT_SERVICE_NAME);
    ADD_NUM("CURLOPT_PIPEWAIT", CURLOPT_PIPEWAIT);
    ADD_NUM("CURLOPT_DEFAULT_PROTOCOL", CURLOPT_DEFAULT_PROTOCOL);
    ADD_NUM("CURLOPT_STREAM_WEIGHT", CURLOPT_STREAM_WEIGHT);
    ADD_NUM("CURLOPT_STREAM_DEPENDS", CURLOPT_STREAM_DEPENDS);
    ADD_NUM("CURLOPT_STREAM_DEPENDS_E", CURLOPT_STREAM_DEPENDS_E);
    ADD_NUM("CURLOPT_TFTP_NO_OPTIONS", CURLOPT_TFTP_NO_OPTIONS);
    ADD_NUM("CURLOPT_CONNECT_TO", CURLOPT_CONNECT_TO);
    ADD_NUM("CURLOPT_TCP_FASTOPEN", CURLOPT_TCP_FASTOPEN);
    ADD_NUM("CURLOPT_KEEP_SENDING_ON_ERROR", CURLOPT_KEEP_SENDING_ON_ERROR);
    ADD_NUM("CURLOPT_PROXY_CAINFO", CURLOPT_PROXY_CAINFO);
    ADD_NUM("CURLOPT_PROXY_CAPATH", CURLOPT_PROXY_CAPATH);
    ADD_NUM("CURLOPT_PROXY_SSL_VERIFYPEER", CURLOPT_PROXY_SSL_VERIFYPEER);
    ADD_NUM("CURLOPT_PROXY_SSL_VERIFYHOST", CURLOPT_PROXY_SSL_VERIFYHOST);
    ADD_NUM("CURLOPT_PROXY_SSLVERSION", CURLOPT_PROXY_SSLVERSION);
    ADD_NUM("CURLOPT_PROXY_TLSAUTH_USERNAME", CURLOPT_PROXY_TLSAUTH_USERNAME);
    ADD_NUM("CURLOPT_PROXY_TLSAUTH_PASSWORD", CURLOPT_PROXY_TLSAUTH_PASSWORD);
    ADD_NUM("CURLOPT_PROXY_TLSAUTH_TYPE", CURLOPT_PROXY_TLSAUTH_TYPE);
    ADD_NUM("CURLOPT_PROXY_SSLCERT", CURLOPT_PROXY_SSLCERT);
    ADD_NUM("CURLOPT_PROXY_SSLCERTTYPE", CURLOPT_PROXY_SSLCERTTYPE);
    ADD_NUM("CURLOPT_PROXY_SSLKEY", CURLOPT_PROXY_SSLKEY);
    ADD_NUM("CURLOPT_PROXY_SSLKEYTYPE", CURLOPT_PROXY_SSLKEYTYPE);
    ADD_NUM("CURLOPT_PROXY_KEYPASSWD", CURLOPT_PROXY_KEYPASSWD);
    ADD_NUM("CURLOPT_PROXY_SSL_CIPHER_LIST", CURLOPT_PROXY_SSL_CIPHER_LIST);
    ADD_NUM("CURLOPT_PROXY_CRLFILE", CURLOPT_PROXY_CRLFILE);
    ADD_NUM("CURLOPT_PROXY_SSL_OPTIONS", CURLOPT_PROXY_SSL_OPTIONS);
    ADD_NUM("CURLOPT_PRE_PROXY", CURLOPT_PRE_PROXY);
    ADD_NUM("CURLOPT_PROXY_PINNEDPUBLICKEY", CURLOPT_PROXY_PINNEDPUBLICKEY);
    ADD_NUM("CURLOPT_ABSTRACT_UNIX_SOCKET", CURLOPT_ABSTRACT_UNIX_SOCKET);
    ADD_NUM("CURLOPT_SUPPRESS_CONNECT_HEADERS", CURLOPT_SUPPRESS_CONNECT_HEADERS);
    ADD_NUM("CURLOPT_REQUEST_TARGET", CURLOPT_REQUEST_TARGET);
    ADD_NUM("CURLOPT_SOCKS5_AUTH", CURLOPT_SOCKS5_AUTH);
    ADD_NUM("CURLOPT_SSH_COMPRESSION", CURLOPT_SSH_COMPRESSION);
    ADD_NUM("CURLOPT_MIMEPOST", CURLOPT_MIMEPOST);
    ADD_NUM("CURLOPT_TIMEVALUE_LARGE", CURLOPT_TIMEVALUE_LARGE);
    ADD_NUM("CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS", CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS);
    ADD_NUM("CURLOPT_RESOLVER_START_FUNCTION", CURLOPT_RESOLVER_START_FUNCTION);
    ADD_NUM("CURLOPT_RESOLVER_START_DATA", CURLOPT_RESOLVER_START_DATA);
    ADD_NUM("CURLOPT_HAPROXYPROTOCOL", CURLOPT_HAPROXYPROTOCOL);
    ADD_NUM("CURLOPT_DNS_SHUFFLE_ADDRESSES", CURLOPT_DNS_SHUFFLE_ADDRESSES);
    ADD_NUM("CURLOPT_TLS13_CIPHERS", CURLOPT_TLS13_CIPHERS);
    ADD_NUM("CURLOPT_PROXY_TLS13_CIPHERS", CURLOPT_PROXY_TLS13_CIPHERS);
    ADD_NUM("CURLOPT_DISALLOW_USERNAME_IN_URL", CURLOPT_DISALLOW_USERNAME_IN_URL);
    ADD_NUM("CURLOPT_DOH_URL", CURLOPT_DOH_URL);
    ADD_NUM("CURLOPT_UPLOAD_BUFFERSIZE", CURLOPT_UPLOAD_BUFFERSIZE);
    ADD_NUM("CURLOPT_UPKEEP_INTERVAL_MS", CURLOPT_UPKEEP_INTERVAL_MS);
    ADD_NUM("CURLOPT_CURLU", CURLOPT_CURLU);
    ADD_NUM("CURLOPT_TRAILERFUNCTION", CURLOPT_TRAILERFUNCTION);
    ADD_NUM("CURLOPT_TRAILERDATA", CURLOPT_TRAILERDATA);
    ADD_NUM("CURLOPT_HTTP09_ALLOWED", CURLOPT_HTTP09_ALLOWED);
    ADD_NUM("CURLOPT_ALTSVC_CTRL", CURLOPT_ALTSVC_CTRL);
    ADD_NUM("CURLOPT_ALTSVC", CURLOPT_ALTSVC);
    ADD_NUM("CURLOPT_MAXAGE_CONN", CURLOPT_MAXAGE_CONN);
    ADD_NUM("CURLOPT_SASL_AUTHZID", CURLOPT_SASL_AUTHZID);
    ADD_NUM("CURLOPT_MAIL_RCPT_ALLLOWFAILS", CURLOPT_MAIL_RCPT_ALLLOWFAILS);
    ADD_NUM("CURLOPT_SSLCERT_BLOB", CURLOPT_SSLCERT_BLOB);
    ADD_NUM("CURLOPT_SSLKEY_BLOB", CURLOPT_SSLKEY_BLOB);
    ADD_NUM("CURLOPT_PROXY_SSLCERT_BLOB", CURLOPT_PROXY_SSLCERT_BLOB);
    ADD_NUM("CURLOPT_PROXY_SSLKEY_BLOB", CURLOPT_PROXY_SSLKEY_BLOB);
    ADD_NUM("CURLOPT_ISSUERCERT_BLOB", CURLOPT_ISSUERCERT_BLOB);
    ADD_NUM("CURLOPT_PROXY_ISSUERCERT", CURLOPT_PROXY_ISSUERCERT);
    ADD_NUM("CURLOPT_PROXY_ISSUERCERT_BLOB", CURLOPT_PROXY_ISSUERCERT_BLOB);
    ADD_NUM("CURLOPT_SSL_EC_CURVES", CURLOPT_SSL_EC_CURVES);
    ADD_NUM("CURLOPT_HSTS_CTRL", CURLOPT_HSTS_CTRL);
    ADD_NUM("CURLOPT_HSTS", CURLOPT_HSTS);
    ADD_NUM("CURLOPT_HSTSREADFUNCTION", CURLOPT_HSTSREADFUNCTION);
    ADD_NUM("CURLOPT_HSTSREADDATA", CURLOPT_HSTSREADDATA);
    ADD_NUM("CURLOPT_HSTSWRITEFUNCTION", CURLOPT_HSTSWRITEFUNCTION);
    ADD_NUM("CURLOPT_HSTSWRITEDATA", CURLOPT_HSTSWRITEDATA);
    ADD_NUM("CURLOPT_AWS_SIGV4", CURLOPT_AWS_SIGV4);
    ADD_NUM("CURLOPT_DOH_SSL_VERIFYPEER", CURLOPT_DOH_SSL_VERIFYPEER);
    ADD_NUM("CURLOPT_DOH_SSL_VERIFYHOST", CURLOPT_DOH_SSL_VERIFYHOST);
    ADD_NUM("CURLOPT_DOH_SSL_VERIFYSTATUS", CURLOPT_DOH_SSL_VERIFYSTATUS);
    ADD_NUM("CURLOPT_CAINFO_BLOB", CURLOPT_CAINFO_BLOB);
    ADD_NUM("CURLOPT_PROXY_CAINFO_BLOB", CURLOPT_PROXY_CAINFO_BLOB);
    ADD_NUM("CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256", CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256);
    ADD_NUM("CURLOPT_PREREQFUNCTION", CURLOPT_PREREQFUNCTION);
    ADD_NUM("CURLOPT_PREREQDATA", CURLOPT_PREREQDATA);
    ADD_NUM("CURLOPT_MAXLIFETIME_CONN", CURLOPT_MAXLIFETIME_CONN);
    ADD_NUM("CURLOPT_MIME_OPTIONS", CURLOPT_MIME_OPTIONS);
    ADD_NUM("CURLOPT_SSH_HOSTKEYFUNCTION", CURLOPT_SSH_HOSTKEYFUNCTION);
    ADD_NUM("CURLOPT_SSH_HOSTKEYDATA", CURLOPT_SSH_HOSTKEYDATA);
    ADD_NUM("CURLOPT_PROTOCOLS_STR", CURLOPT_PROTOCOLS_STR);
    ADD_NUM("CURLOPT_REDIR_PROTOCOLS_STR", CURLOPT_REDIR_PROTOCOLS_STR);

    ADD_NUM("CURLE_OK", CURLE_OK);
    ADD_NUM("CURLE_UNSUPPORTED_PROTOCOL", CURLE_UNSUPPORTED_PROTOCOL);
    ADD_NUM("CURLE_FAILED_INIT", CURLE_FAILED_INIT);
    ADD_NUM("CURLE_URL_MALFORMAT", CURLE_URL_MALFORMAT);
    ADD_NUM("CURLE_NOT_BUILT_IN", CURLE_NOT_BUILT_IN);
    ADD_NUM("CURLE_COULDNT_RESOLVE_PROXY", CURLE_COULDNT_RESOLVE_PROXY);
    ADD_NUM("CURLE_COULDNT_RESOLVE_HOST", CURLE_COULDNT_RESOLVE_HOST);
    ADD_NUM("CURLE_COULDNT_CONNECT", CURLE_COULDNT_CONNECT);
    ADD_NUM("CURLE_WEIRD_SERVER_REPLY", CURLE_WEIRD_SERVER_REPLY);
    ADD_NUM("CURLE_REMOTE_ACCESS_DENIED", CURLE_REMOTE_ACCESS_DENIED);
    ADD_NUM("CURLE_FTP_ACCEPT_FAILED", CURLE_FTP_ACCEPT_FAILED);
    ADD_NUM("CURLE_FTP_WEIRD_PASS_REPLY", CURLE_FTP_WEIRD_PASS_REPLY);
    ADD_NUM("CURLE_FTP_ACCEPT_TIMEOUT", CURLE_FTP_ACCEPT_TIMEOUT);
    ADD_NUM("CURLE_FTP_WEIRD_PASV_REPLY", CURLE_FTP_WEIRD_PASV_REPLY);
    ADD_NUM("CURLE_FTP_WEIRD_227_FORMAT", CURLE_FTP_WEIRD_227_FORMAT);
    ADD_NUM("CURLE_FTP_CANT_GET_HOST", CURLE_FTP_CANT_GET_HOST);
    ADD_NUM("CURLE_HTTP2", CURLE_HTTP2);
    ADD_NUM("CURLE_FTP_COULDNT_SET_TYPE", CURLE_FTP_COULDNT_SET_TYPE);
    ADD_NUM("CURLE_PARTIAL_FILE", CURLE_PARTIAL_FILE);
    ADD_NUM("CURLE_FTP_COULDNT_RETR_FILE", CURLE_FTP_COULDNT_RETR_FILE);
    ADD_NUM("CURLE_OBSOLETE20", CURLE_OBSOLETE20);
    ADD_NUM("CURLE_QUOTE_ERROR", CURLE_QUOTE_ERROR);
    ADD_NUM("CURLE_HTTP_RETURNED_ERROR", CURLE_HTTP_RETURNED_ERROR);
    ADD_NUM("CURLE_WRITE_ERROR", CURLE_WRITE_ERROR);
    ADD_NUM("CURLE_OBSOLETE24", CURLE_OBSOLETE24);
    ADD_NUM("CURLE_UPLOAD_FAILED", CURLE_UPLOAD_FAILED);
    ADD_NUM("CURLE_READ_ERROR", CURLE_READ_ERROR);
    ADD_NUM("CURLE_OUT_OF_MEMORY", CURLE_OUT_OF_MEMORY);
    ADD_NUM("CURLE_OPERATION_TIMEDOUT", CURLE_OPERATION_TIMEDOUT);
    ADD_NUM("CURLE_OBSOLETE29", CURLE_OBSOLETE29);
    ADD_NUM("CURLE_FTP_PORT_FAILED", CURLE_FTP_PORT_FAILED);
    ADD_NUM("CURLE_FTP_COULDNT_USE_REST", CURLE_FTP_COULDNT_USE_REST);
    ADD_NUM("CURLE_OBSOLETE32", CURLE_OBSOLETE32);
    ADD_NUM("CURLE_RANGE_ERROR", CURLE_RANGE_ERROR);
    ADD_NUM("CURLE_HTTP_POST_ERROR", CURLE_HTTP_POST_ERROR);
    ADD_NUM("CURLE_SSL_CONNECT_ERROR", CURLE_SSL_CONNECT_ERROR);
    ADD_NUM("CURLE_BAD_DOWNLOAD_RESUME", CURLE_BAD_DOWNLOAD_RESUME);
    ADD_NUM("CURLE_FILE_COULDNT_READ_FILE", CURLE_FILE_COULDNT_READ_FILE);
    ADD_NUM("CURLE_LDAP_CANNOT_BIND", CURLE_LDAP_CANNOT_BIND);
    ADD_NUM("CURLE_LDAP_SEARCH_FAILED", CURLE_LDAP_SEARCH_FAILED);
    ADD_NUM("CURLE_OBSOLETE40", CURLE_OBSOLETE40);
    ADD_NUM("CURLE_FUNCTION_NOT_FOUND", CURLE_FUNCTION_NOT_FOUND);
    ADD_NUM("CURLE_ABORTED_BY_CALLBACK", CURLE_ABORTED_BY_CALLBACK);
    ADD_NUM("CURLE_BAD_FUNCTION_ARGUMENT", CURLE_BAD_FUNCTION_ARGUMENT);
    ADD_NUM("CURLE_OBSOLETE44", CURLE_OBSOLETE44);
    ADD_NUM("CURLE_INTERFACE_FAILED", CURLE_INTERFACE_FAILED);
    ADD_NUM("CURLE_OBSOLETE46", CURLE_OBSOLETE46);
    ADD_NUM("CURLE_TOO_MANY_REDIRECTS", CURLE_TOO_MANY_REDIRECTS);
    ADD_NUM("CURLE_UNKNOWN_OPTION", CURLE_UNKNOWN_OPTION);
    ADD_NUM("CURLE_SETOPT_OPTION_SYNTAX", CURLE_SETOPT_OPTION_SYNTAX);
    ADD_NUM("CURLE_OBSOLETE50", CURLE_OBSOLETE50);
    ADD_NUM("CURLE_OBSOLETE51", CURLE_OBSOLETE51);
    ADD_NUM("CURLE_GOT_NOTHING", CURLE_GOT_NOTHING);
    ADD_NUM("CURLE_SSL_ENGINE_NOTFOUND", CURLE_SSL_ENGINE_NOTFOUND);
    ADD_NUM("CURLE_SSL_ENGINE_SETFAILED", CURLE_SSL_ENGINE_SETFAILED);
    ADD_NUM("CURLE_SEND_ERROR", CURLE_SEND_ERROR);
    ADD_NUM("CURLE_RECV_ERROR", CURLE_RECV_ERROR);
    ADD_NUM("CURLE_OBSOLETE57", CURLE_OBSOLETE57);
    ADD_NUM("CURLE_SSL_CERTPROBLEM", CURLE_SSL_CERTPROBLEM);
    ADD_NUM("CURLE_SSL_CIPHER", CURLE_SSL_CIPHER);
    ADD_NUM("CURLE_PEER_FAILED_VERIFICATION", CURLE_PEER_FAILED_VERIFICATION);
    ADD_NUM("CURLE_BAD_CONTENT_ENCODING", CURLE_BAD_CONTENT_ENCODING);
    ADD_NUM("CURLE_OBSOLETE62", CURLE_OBSOLETE62);
    ADD_NUM("CURLE_FILESIZE_EXCEEDED", CURLE_FILESIZE_EXCEEDED);
    ADD_NUM("CURLE_USE_SSL_FAILED", CURLE_USE_SSL_FAILED);
    ADD_NUM("CURLE_SEND_FAIL_REWIND", CURLE_SEND_FAIL_REWIND);
    ADD_NUM("CURLE_SSL_ENGINE_INITFAILED", CURLE_SSL_ENGINE_INITFAILED);
    ADD_NUM("CURLE_LOGIN_DENIED", CURLE_LOGIN_DENIED);
    ADD_NUM("CURLE_TFTP_NOTFOUND", CURLE_TFTP_NOTFOUND);
    ADD_NUM("CURLE_TFTP_PERM", CURLE_TFTP_PERM);
    ADD_NUM("CURLE_REMOTE_DISK_FULL", CURLE_REMOTE_DISK_FULL);
    ADD_NUM("CURLE_TFTP_ILLEGAL", CURLE_TFTP_ILLEGAL);
    ADD_NUM("CURLE_TFTP_UNKNOWNID", CURLE_TFTP_UNKNOWNID);
    ADD_NUM("CURLE_REMOTE_FILE_EXISTS", CURLE_REMOTE_FILE_EXISTS);
    ADD_NUM("CURLE_TFTP_NOSUCHUSER", CURLE_TFTP_NOSUCHUSER);
    ADD_NUM("CURLE_OBSOLETE75", CURLE_OBSOLETE75);
    ADD_NUM("CURLE_OBSOLETE76", CURLE_OBSOLETE76);
    ADD_NUM("CURLE_SSL_CACERT_BADFILE", CURLE_SSL_CACERT_BADFILE);
    ADD_NUM("CURLE_REMOTE_FILE_NOT_FOUND", CURLE_REMOTE_FILE_NOT_FOUND);
    ADD_NUM("CURLE_SSH", CURLE_SSH);
    ADD_NUM("CURLE_SSL_SHUTDOWN_FAILED", CURLE_SSL_SHUTDOWN_FAILED);
    ADD_NUM("CURLE_AGAIN", CURLE_AGAIN);
    ADD_NUM("CURLE_SSL_CRL_BADFILE", CURLE_SSL_CRL_BADFILE);
    ADD_NUM("CURLE_SSL_ISSUER_ERROR", CURLE_SSL_ISSUER_ERROR);
    ADD_NUM("CURLE_FTP_PRET_FAILED", CURLE_FTP_PRET_FAILED);
    ADD_NUM("CURLE_RTSP_CSEQ_ERROR", CURLE_RTSP_CSEQ_ERROR);
    ADD_NUM("CURLE_RTSP_SESSION_ERROR", CURLE_RTSP_SESSION_ERROR);
    ADD_NUM("CURLE_FTP_BAD_FILE_LIST", CURLE_FTP_BAD_FILE_LIST);
    ADD_NUM("CURLE_CHUNK_FAILED", CURLE_CHUNK_FAILED);
    ADD_NUM("CURLE_NO_CONNECTION_AVAILABLE", CURLE_NO_CONNECTION_AVAILABLE);
    ADD_NUM("CURLE_SSL_PINNEDPUBKEYNOTMATCH", CURLE_SSL_PINNEDPUBKEYNOTMATCH);
    ADD_NUM("CURLE_SSL_INVALIDCERTSTATUS", CURLE_SSL_INVALIDCERTSTATUS);
    ADD_NUM("CURLE_HTTP2_STREAM", CURLE_HTTP2_STREAM);
    ADD_NUM("CURLE_RECURSIVE_API_CALL", CURLE_RECURSIVE_API_CALL);
    ADD_NUM("CURLE_AUTH_ERROR", CURLE_AUTH_ERROR);
    ADD_NUM("CURLE_HTTP3", CURLE_HTTP3);
    ADD_NUM("CURLE_QUIC_CONNECT_ERROR", CURLE_QUIC_CONNECT_ERROR);
    ADD_NUM("CURLE_PROXY", CURLE_PROXY);
    ADD_NUM("CURLE_SSL_CLIENTCERT", CURLE_SSL_CLIENTCERT);
    ADD_NUM("CURLE_UNRECOVERABLE_POLL", CURLE_UNRECOVERABLE_POLL);

    ADD_FUN("curl_easy_init", lua_curl_easy_init);
    ADD_FUN("curl_easy_cleanup", lua_curl_easy_cleanup);
    ADD_FUN("curl_easy_perform", lua_curl_easy_perform);
    ADD_FUN("curl_easy_setopt", lua_curl_easy_setopt);
    ADD_FUN("curl_easy_strerror", lua_curl_easy_strerror);

    // Pop the global table from the stack again
    LUA->Pop();
    return 0;
}

GMOD_MODULE_CLOSE()
{
    curl_global_cleanup();
    return 0;
}
