name: New Commit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Build
      run: |
        echo "GMCURL_VERSION=$(git describe --tags | sed 's/^v//')" >> $GITHUB_ENV
        ./dist.sh

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: gmod-gmcurl-${{ env.GMCURL_VERSION }}-binaries
        path: dist/*

  format:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install clang-format
        run: |
          curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main'
          sudo apt-get update
          sudo apt-get install -y clang-format-15

      - name: Run clang-format
        run: clang-format-15 -style=file -i src/*.cpp src/*.h

      - name: Check for changes
        run: git diff --exit-code
